FROM coreoasis/model_worker:latest 

WORKDIR /home/worker

#RUN pip install --upgrade pip==20.0.2

COPY ./requirements.txt /tmp/ 
RUN pip install -r /tmp/requirements.txt

COPY ./complex_model /home/worker/model/complex_model
COPY ./setup.py /home/worker/model/setup.py
RUN pip install -e /home/worker/model

COPY ./meta-data/model_settings.json /home/worker/model/meta-data/model_settings.json
COPY ./oasislmf_deploy.json /home/worker/model/oasislmf.json

ENTRYPOINT ./startup.sh
